### ISSUE TITLE
When running the script,I get these patching error messages.thanks

### ISSUE THREAD

**Issue by windliao** [falafalafala1668/OpenWrt-UEFI-Support#1]
patching file config/Config-images.in
Hunk #4 FAILED at 266.
1 out of 4 hunks FAILED -- saving rejects to file config/Config-images.in.rej
patching file package/base-files/files/lib/upgrade/common.sh
Unreversed patch detected!  Ignore -R? [n] n
Apply anyway? [n] n
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file package/base-files/files/lib/upgrade/common.sh.rej
patching file target/linux/x86/image/Makefile
Unreversed patch detected!  Ignore -R? [n] n
Apply anyway? [n] n
Skipping patch.
6 out of 6 hunks ignored -- saving rejects to file target/linux/x86/image/Makefile.rej
patching file tools/Makefile
Hunk #1 FAILED at 25.
Hunk #2 FAILED at 79.
Hunk #3 FAILED at 125.
Hunk #4 FAILED at 154.
4 out of 4 hunks FAILED -- saving rejects to file tools/Makefile.rej
From OpenWrt-UEFI-Support
 * branch                  HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories
patching file config/Config-images.in
Hunk #4 FAILED at 268.
1 out of 4 hunks FAILED -- saving rejects to file config/Config-images.in.rej
patching file package/base-files/files/lib/upgrade/common.sh
patching file target/linux/x86/image/Makefile
Hunk #3 FAILED at 44.
Hunk #4 FAILED at 93.
Hunk #5 FAILED at 127.
Hunk #6 FAILED at 172.
4 out of 6 hunks FAILED -- saving rejects to file target/linux/x86/image/Makefile.rej
patching file tools/Makefile
Hunk #1 FAILED at 25.
1 out of 4 hunks FAILED -- saving rejects to file tools/Makefile.rej
lede@openwrt-compiler:~/openwrt$ ./OpenWrt-UEFI-Support/RunMe.sh apply
patching file config/Config-images.in
Hunk #4 FAILED at 266.
1 out of 4 hunks FAILED -- saving rejects to file config/Config-images.in.rej
patching file package/base-files/files/lib/upgrade/common.sh
patching file target/linux/x86/image/Makefile
Hunk #3 FAILED at 41.
Hunk #4 FAILED at 156.
Hunk #5 FAILED at 192.
Hunk #6 FAILED at 256.
4 out of 6 hunks FAILED -- saving rejects to file target/linux/x86/image/Makefile.rej
patching file tools/Makefile
Hunk #1 FAILED at 25.
Hunk #2 succeeded at 78 (offset -1 lines).
Hunk #3 succeeded at 123 (offset -1 lines).
Hunk #4 succeeded at 152 (offset -1 lines).
1 out of 4 hunks FAILED -- saving rejects to file tools/Makefile.rej
From OpenWrt-UEFI-Support
 * branch                  HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories
patching file config/Config-images.in
Hunk #4 FAILED at 268.
1 out of 4 hunks FAILED -- saving rejects to file config/Config-images.in.rej
patching file package/base-files/files/lib/upgrade/common.sh
patching file target/linux/x86/image/Makefile
Hunk #3 FAILED at 44.
Hunk #4 FAILED at 93.
Hunk #5 FAILED at 127.
Hunk #6 FAILED at 172.
4 out of 6 hunks FAILED -- saving rejects to file target/linux/x86/image/Makefile.rej
patching file tools/Makefile
Hunk #1 FAILED at 25.
1 out of 4 hunks FAILED -- saving rejects to file tools/Makefile.rej

**Comment by falafalafala1668** [comment]
Give me some time to check. Thank you.

**Comment by windliao** [comment]
I'm using master

**Comment by windliao** [comment]
now the error messages updated:
lede@openwrt-compiler:~/openwrt$ chmod +x ./OpenWrt-UEFI-Support/RunMe.sh
lede@openwrt-compiler:~/openwrt$ ./OpenWrt-UEFI-Support/RunMe.sh apply
Updating patches
./OpenWrt-UEFI-Support/RunMe.sh: 11: ./OpenWrt-UEFI-Support/RunMe.sh: pushd: not found
Already up to date.
./OpenWrt-UEFI-Support/RunMe.sh: 13: ./OpenWrt-UEFI-Support/RunMe.sh: popd: not found
patching file config/Config-images.in
Hunk #3 FAILED at 249.
Hunk #4 FAILED at 274.
2 out of 4 hunks FAILED -- saving rejects to file config/Config-images.in.rej
patching file package/base-files/files/lib/upgrade/common.sh
patching file target/linux/x86/image/Makefile
Hunk #3 FAILED at 44.
Hunk #4 FAILED at 93.
Hunk #5 FAILED at 127.
Hunk #6 FAILED at 172.
4 out of 6 hunks FAILED -- saving rejects to file target/linux/x86/image/Makefile.rej
patching file tools/Makefile
Hunk #1 FAILED at 25.
Hunk #3 FAILED at 124.
Hunk #4 FAILED at 153.
3 out of 4 hunks FAILED -- saving rejects to file tools/Makefile.rej

**Comment by falafalafala1668** [comment]
Because I already fix it, give me some time.
Thanks.

**Comment by falafalafala1668** [comment]
OK, you can test it.Apply before please restore original files:
```
git checkout package/boot/grub2/Makefile
git checkout config/Config-images.in
git checkout tools/Makefile
git checkout target/linux/x86/image/Makefile
```
and update my code then run:
```
./OpenWrt-UEFI-Support/RunMe.sh apply
```
I'm looking forward to your good news.

**Comment by falafalafala1668** [comment]
I found some issues, please check later.

**Comment by windliao** [comment]
Great,it works!
There're the messages:
lede@openwrt-compiler:~/openwrt$ ./OpenWrt-UEFI-Support/RunMe.sh apply
###### Applying patches ######
patching file config/Config-images.in
patching file target/linux/x86/image/Makefile
patching file tools/Makefile
patching file package/boot/grub2/Makefile

**Comment by falafalafala1668** [comment]
I'm glad to hear that, and I'm looking forward to running on machine.
If have any problems, please report me ASAP.
Waiting for your good news.

**Comment by gitxmax** [comment]
having the same issue, tried all the banches offered
As well the solution offered:

`git checkout package/boot/grub2/Makefile
git checkout config/Config-images.in
git checkout tools/Makefile
git checkout target/linux/x86/image/Makefile
and update my codes then run:

./OpenWrt-UEFI-Support/RunMe.sh apply`

I'm not so strong with the git commands, whats the "and update my codes then run:" implies?
Also, why does it say "Reversed (or previously applied) patch detected!" if no patch previously applied?

**Comment by falafalafala1668** [comment]
First question, Those git commands are to make sure that the source file hasn't changed so that I can apply my patch without errors.
Second question, since the official code is often updated, some differences may lead to patch failure. I haven't found the perfect way to patch. If you suspect that my patch will cause problems, the git command above is to restore to the official original file.
Please let me know if you have a good implementation method, thank you.

**Comment by falafalafala1668** [comment]
If you have any questions, please open new issue. Thanks

**Comment by Anaelle-T** [comment]
HI, I need help with this message:
  "Skipping patch.
	1 out of 1 hunk ignored -- saving rejects to file sph2pipe.c.rej
	patching file ulaw.h
	Makefile:144: recipe for target 'sph2pipe_v2.5/.patched' failed
	make: *** [sph2pipe_v2.5/.patched] Error 1
"
When I try to install Kaldi

**Comment by romadomaa** [comment]
> HI, I need help with this message:
> "Skipping patch.
> 1 out of 1 hunk ignored -- saving rejects to file sph2pipe.c.rej
> patching file ulaw.h
> Makefile:144: recipe for target 'sph2pipe_v2.5/.patched' failed
> make: *** [sph2pipe_v2.5/.patched] Error 1
> "
> When I try to install Kaldi

me too...

**Comment by falafalafala1668** [comment]
Is master branch?

**Comment by kompotiks** [comment]
Yes

**Comment by falafalafala1668** [comment]
Master branch has officially supported UEFI. The Patch only working in
19.07 and 18.06.

**Comment by ChengWang-hit** [comment]
> Master branch has officially supported UEFI. The Patch only working in 19.07 and 18.06.

so how to solve this problem? I use 20.04.

**Comment by falafalafala1668** [comment]
20.04?
The patch is made for Openwrt, not Ubuntu.If you have been patched this for master branch of Openwrt,please restore it.
