### ISSUE TITLE
Can't boot with openwrt master branch

### ISSUE THREAD

**Issue by garypang13** [falafalafala1668/OpenWrt-UEFI-Support#2]
The cmd prompt show "booting openwrt" then reboot automatically,and repeat this process.

**Comment by falafalafala1668** [comment]
Can I see your startup log. Thanks.

**Comment by falafalafala1668** [comment]
I'm sorry to hear that. Please give me some time to find the problem. 
Thank you.

**Comment by garypang13** [comment]
OpenWrt-UEFI-Support and openwrt both are master branch,the openwrt kernel version is 5.4.
Thanks.

**Comment by falafalafala1668** [comment]
If possible, can you take a picture of what the screen shows at the instant of the reboot?

**Comment by garypang13** [comment]
![aa](https://user-images.githubusercontent.com/48883331/77177532-a32c8f80-6b00-11ea-8dde-48be45a129df.png)

**Comment by falafalafala1668** [comment]
I have updated the new source code and tested it without any problems. Please restore the patch, update it and then apply the patch.
Thanks!

Restore:
```
./OpenWrt-UEFI-Support/RunMe.sh restore
```

Update:
```
./OpenWrt-UEFI-Support/RunMe.sh update
```

Apply:
```
./OpenWrt-UEFI-Support/RunMe.sh apply
```

**Comment by garypang13** [comment]
Much appreciated!
 I'll feedback later.

**Comment by garypang13** [comment]
不好意思,還是報相同的錯,
我是在pve虛擬環境下測試的.
相同環境下我用 https://drive.google.com/open?id=1ogJrZ1jgFj-AfBsFgYLppxX1qZ6jPvJc 這個支持uefi的firmware可以正常啓動運行.
我的編譯源碼和編譯好的firmware在此 https://github.com/garypang13/Actions-OpenWrt-Snapshot/releases
感謝

**Comment by falafalafala1668** [comment]
給我一些時間測試一下，抱歉

**Comment by falafalafala1668** [comment]
抱歉，我的Proxmox存在一些問題，無法在我這測試。
新的原始碼已上傳，請你再嘗試一次。
謝謝

**Comment by garypang13** [comment]
還是同樣的錯誤哦.

**Comment by falafalafala1668** [comment]
抱歉，等我弄好PVE再試試吧

**Comment by falafalafala1668** [comment]
其他的會這樣嗎？還是只是這個會重啟呢？

**Comment by garypang13** [comment]
只是這個, 相同環境下我用自带UEFI支持的lean源码 https://github.com/coolsnowwolf/lede 編譯的uefi firmware可以正常運行.
我用官方源碼編譯的legacy firmware在pve下也能正常運行.

**Comment by falafalafala1668** [comment]
好的👌，抱歉

**Comment by falafalafala1668** [comment]
我使用原版和UEFI都出現重啟現象，lean還沒時間測試，今天研究許久都有些摸不著腦袋😅，對pve也不大熟悉，一般使用vmware，所以其他的並不暸解。
這個問題我會留意，如果你有主意請告訴我。十分抱歉。
再次感謝你的問題。
pve:proxmox-ve_6.1-1

**Comment by garypang13** [comment]
我剛下載了官方原版鏡像 https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz 測試了在我的PVE中是可以正常啓動運行的.
![2020-3-22 23-2-41](https://user-images.githubusercontent.com/48883331/77252821-6cd24a00-6c91-11ea-9f5b-4b38945ed940.png)
![2020-3-22 23-0-59](https://user-images.githubusercontent.com/48883331/77252825-7065d100-6c91-11ea-98fc-1f6130b928f0.png)
如果你那邊原版也有問題的話,肯定是你PVE環境的問題哦.
我是通過 ./img2kvm openwrt-x86-64-generic-squashfs-combined.img 102(vm id) 命令寫入img鏡像到pve的.

**Comment by falafalafala1668** [comment]
我的和你基本一樣，只是少了那個EFI磁碟和網路，不知道有沒有關係，少網路卡是肯定沒事的，實機和VMware 都能正常運作。pve也是安裝在VMware
Fusion上的，可能有不確定因素。今天測試還發現關不掉虛機，是今天運氣不好嗎😭

**Comment by falafalafala1668** [comment]
身邊都是Mac，實機裝pve不大方便，比較尷尬

**Comment by garypang13** [comment]
EFI磁碟也肯定沒事的,那個是我用來測試uefi才需要的.
最有可能是pve安裝在VMware Fusion上導致的.

**Comment by falafalafala1668** [comment]
了解，我會再試一下。可能會久些，得上課🤓

**Comment by falafalafala1668** [comment]
已經查到原因：UEFI下會載入顯示卡驅動程式，可能是pve的顯示卡有問題導致panic。
解決方法是添加nomodeset參數停止使用顯示卡驅動程式（在Target Images -> Extra kernel boot options)

**Comment by falafalafala1668** [comment]
<img width="1341" alt="Screenshot 2020-03-23 at 16 48 06" src="https://user-images.githubusercontent.com/57652508/77298856-8376b080-6d26-11ea-878c-c567ccf60550.png">
<img width="1341" alt="Screenshot 2020-03-23 at 16 43 51" src="https://user-images.githubusercontent.com/57652508/77298930-a1dcac00-6d26-11ea-8897-92f4d0e5ff72.png">
<img width="1341" alt="Screenshot 2020-03-23 at 16 48 53" src="https://user-images.githubusercontent.com/57652508/77298940-a7d28d00-6d26-11ea-8bc8-609ba9fba055.png">

**Comment by garypang13** [comment]
Bingo!
非常感謝你的耐心幫助!

**Comment by xuhuanxxx** [comment]
无限自动重启的问题我也遇到了，不过我是在Esxi上测试的combined-squashfs.vmdk，纯官方源码和OpenWrt-UEFI-Support apply过的两种环境下各编译了一个版本，都是同样的问题，理论上应该是openwrt自己的问题，和OpenWrt-UEFI-Support无关吧？

![image](https://user-images.githubusercontent.com/4946617/77497436-41fe1680-6e88-11ea-9048-0bc47c5a42b6.png)

**Comment by falafalafala1668** [comment]
確實沒有關係，不過你這個panic的點看似虛機硬碟Bus相關的Drivers沒有或是Image損壞了，可以重新生成並改成IDE試試。
