### ISSUE TITLE
在官方19.07.8源码测试失败

### ISSUE THREAD

**Issue by wlshdjj** [falafalafala1668/OpenWrt-UEFI-Support#6]
可生成固件，但无法引导启动，只见光标在闪，并无任何文字错误提示。查看写的优盘分区情况和官方21的efi固件写的盘不同。

**Comment by falafalafala1668** [comment]
换虚拟机试试？直接上21吧，都支持uefi了。这都准备Achieve了🤣

**Comment by wlshdjj** [comment]
就是用了21发现实在不堪用，n多问题。稳定18才是首选，19是无奈。

**Comment by falafalafala1668** [comment]
我也有18的分支，不过很久没维护了，但是可以试一下。
21一出我就更了，也是用我这个uefi直升上去的，似乎挺稳定的，这个都打算归档不理了。不过最近我没空，有时间会看看是啥问题。抱歉

**Comment by wlshdjj** [comment]
辛苦你了！初步判断是引导分区错误所致。
我看了18是两年前的了，现在不知是否能用所以没测试。
21最大问题是mac80211，会突发频繁报错，同时无线短暂断线，其他反而还好。我翻看了op官方都无人提交同样的错误，我又没有op账号，因此是不可能得到修复的了。我用的是官方源码，按理会有人触发同样的报错才对，但目前无见到。

**Comment by falafalafala1668** [comment]
1、应该能用，到时我两个都看看
2、x86的无线确实拉😂，之前用了一次就果断放弃了，无线部分还是得给专业的，x86老老实实当路由比较好。

**Comment by wlshdjj** [comment]
不，18，19的无线是很好的，我都用了一两年了，并不比一般刷op的无线路由器差。只是21却有问题。

**Comment by falafalafala1668** [comment]
久等了，挤了亿点时间来补了一下19.07的，可以试试，建议重新拉源码来。

18.06也可以了

**Comment by wlshdjj** [comment]
非常感谢老哥！

**Comment by falafalafala1668** [comment]
有问题再提，这个先关啦

**Comment by wlshdjj** [comment]
19.07.8试了依然失败。

**Comment by wlshdjj** [comment]
21的分区有3个：
 序号   名称               文件系统   引导  标识   起始柱面   磁头   扇区   终止柱面   磁头   扇区     容量
   0   分区(0)              BIOS Boo   00    FF           0      0     35          0      8      8   239.0KB
   1   ESP(G:)              FAT16      00    06           0      8      9          2     18     16    16.0MB
   2   分区(2)              MS Basic   00    FF           2     26     25        114     73     23   880.0MB

19的分区只有2个：
 序号   名称               文件系统   引导  标识   起始柱面   磁头   扇区   终止柱面   磁头   扇区     容量
   0   ESP(0)               FAT16      00    06           0      8      9          2     18     16    16.0MB
   1   Linux filesystem(1)  Unknown    00    FF           2     26     25        114     73     23   880.0MB

和之前一样，不能启动，在虚拟机上测试只有光标在闪，没有报错信息。

**Comment by falafalafala1668** [comment]
1、分区那个没关系的，既然都用efi了能找到efi分区还有bootxXX.efi（类似）就行了。
2、两种我都测过是可以才发出来了，看来还得抽空看看。我最后还以防万一删了重新拉了一份再测的，会不会是你那哪个地方搞错了🤔
3、虚拟机：VMware Fusion 12。
4、那个光标是在倒数5秒后还是过完自检就有的？
5、你测试环境是啥

**Comment by wlshdjj** [comment]
没有，开着过了十几分钟了，还在闪，没有报错信息。2还是3分区应该没什么关系，应该问题在引导路径上，对efi引导没研究过，因此说不出所以然。
虚拟机是VMware® Workstation 15 Pro
我使用的是物理硬盘，优盘直接写盘运行，不是转换为vmdk。官方21编译出来是能启动的。

**Comment by wlshdjj** [comment]
翻看了下，boot下无vmlinuz文件、grub下只有grub.cfg，无其它文件。内核没写进去，所以不能启动。而21有boot.img、core.img、grub.cfg。没有写进去内核，莫名其妙。

**Comment by wlshdjj** [comment]
18069我试了也同样表现。盯着屏幕看编译过程，摘出两个主要报错：
cp -fpR /home/xxx/18069/staging_dir/target-x86_64_musl/root-x86/boot/. /home/xxx/18069/build_dir/target-x86_64_musl/linux-x86_64/root.grub/boot/ -------这个 target-x86_64_musl/root-x86/boot/.  （实际上staging_dir/target-x86_64_musl/root-x86/下面不存在这个boot目录）  、  /root.grub/  路径是错误的。不过我从21的分区把grub目录下面文件拿出来写进去，依然无法启动。
cp: cannot stat '/home/xxx/18069/staging_dir/target-x86_64_musl/root-x86/boot/.': No such file or directory
Makefile:262: recipe for target 'install-images' failed
make[5]: [install-images] Error 1 (ignored)

sgdisk -t 1:EF00 "/home/xxx/18069/bin/targets/x86/64/openwrt-x86-64-squashfs-combined-efi.img"
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.

不知是否有关。
看来还是不要搞了。

**Comment by falafalafala1668** [comment]
好，今晚我再看看，就不信搞不定了。
抱歉啊，还是没解决😅

**Comment by wlshdjj** [comment]
/root.grub/ 路径是错误的。---------我进去翻了，这个路径没错，的确有root.grub
不过/staging_dir/target-x86_64_musl/root-x86/boot 的确是没有。

不过我现在觉得问题不在上面这两处。
我觉得抱歉，本来你不用再费这心思。

**Comment by wlshdjj** [comment]
我重复试，现在18、19都有vmlinuz文件了。问题应该在vmlinuz的格式上。
试了，也不是这里。唉，算了。

**Comment by falafalafala1668** [comment]
1、没关系，补补bug长身体。
2、刚刚重新编译了一下，补了两个问题，但是还是与你的问题没关系（眼睛有洞了属于是）
3、我真机虚机都跑过了，毫无问题，包括vmdk，usb直连，硬盘直通。
4、我以防万一，重新装了新系统全部从0开始重新编译一遍看看，可能需要一些时间
5、突然好奇你的虚拟机的配置怎样的，还有在其他平台跑过吗？

**Comment by falafalafala1668** [comment]
就在我苦苦寻找我的问题的时候，我打开了Windows装了个VMware workstation 15才发现，这货新建虚机向导没有显示BIOS模式选项（Fusion是有提示你选Legacy BIOS或者是EFI，也有可能我的操作不对）导致我也遇到闪光标，才发现这是BIOS模式……所以我一直以为你是在EFI模式下闪的。这个补丁的EFI固件只支持EFI，官方的是两者兼备（都用EFI了还要BIOS干啥，其实也是为了维护方便😅），你检查一下你的虚拟机设置是不是EFI模式就行。
![image](https://user-images.githubusercontent.com/57652508/138666257-03d7784b-8ea4-4906-be11-eb4632c39476.png)

**Comment by wlshdjj** [comment]
居然是VM这么一个坑！

**Comment by wlshdjj** [comment]
按上面说的做启动成功。抱歉给你找来这么多麻烦！

**Comment by falafalafala1668** [comment]
没关系，弄好就行。
有问题再提，先关啦
