### ISSUE TITLE
19.07.8试了依然失败

### ISSUE THREAD

**Issue by wlshdjj** [falafalafala1668/OpenWrt-UEFI-Support#7]
21的分区有3个：
 序号   名称               文件系统   引导  标识   起始柱面   磁头   扇区   终止柱面   磁头   扇区     容量
   0   分区(0)              BIOS Boo   00    FF           0      0      35          0      8       8    239.0KB
   1   ESP(G:)              FAT16        00    06           0      8        9          2     18     16    16.0MB
   2   分区(2)              MS Basic    00    FF           2     26     25      114     73     23   880.0MB

19的分区只有2个：
 序号   名称               文件系统   引导  标识   起始柱面   磁头   扇区   终止柱面   磁头   扇区     容量
   0   ESP(0)               FAT16      00    06           0      8      9          2     18     16    16.0MB
   1   Linux filesystem(1)  Unknown    00    FF           2     26     25        114     73     23   880.0MB

和之前一样，不能启动，在虚拟机上测试只有光标在闪，没有报错信息。如果比较麻烦，就算了不要搞了。
18还没测试。

**Comment by falafalafala1668** [comment]
在[#6](https://github.com/falafalafala1668/OpenWrt-UEFI-Support/issues/6)那说就行，这个先关了
